### ISSUE TITLE
Implementation of online_mean and online_std

### ISSUE THREAD

**Issue by lyuqin** [CSE-O1/cs207project#2]
The requirement is:
Add mean and std method interfaces at the appropriate places in the hierarchy. These methods should return floating point numbers. (an optional chunk argument is needed in some cases) Also add an online_mean and online_std for StreamTimeSeriesInterface time-series, which themselves return the appropriate time-series. These "online" methods should return new SimulatedTimeSeries of the appropriate type, and when produce is called on them, should produce chunk means and standard deviations, starting from the current state of the time series. (notice that this will be the meaning of mean and std with non default chunk as well: ie, the last chunk observations' statistic )

**Comment by xwang146** [comment]
My opinion is that you should implement the mean and std methods into SizedContainerTimeSeriesInterface, with a optional chunk parameter. You should return the last chunk's statistic (i.e. if chunk=len-1, mean method returns the mean of values[0]-values[n-2] of that timeseries). For "online" methods, I think you implementation is fine, as long as they pass all tests.
